# Generated by Django 3.0.2 on 2020-03-07 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grade_A', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grade_A.Review'),
        ),
    ]
